Repository CS342/2024-Stronger, pull requests merged in 2024-01, with the labels that each got.

#2 Fix Firebase Project ID
  .firebaserc
  Stronger/Supporting Files/GoogleService-Info.plist
Labels: bug

#11 Update README & CodeCov Setup
  README.md
  codecov.yml
Labels: documentation

#5 changes to icons and description on welcome page
  Stronger/Onboarding/Welcome.swift
  Stronger/Resources/Localizable.xcstrings
Labels: enhancement

#3 Assignment 1 Task 3: Add health data authorization and remove notifications
  Stronger.xcodeproj/project.pbxproj
  Stronger/Onboarding/NotificationPermissions.swift
  Stronger/Onboarding/OnboardingFlow.swift
  Stronger/Resources/Localizable.xcstrings
  Stronger/StrongerDelegate.swift
Labels: enhancement
